"""
Device model.

Tracks registered client devices (mobile / web) for each user.
A device is identified by a ``device_fingerprint`` that the client SDK
generates once and persists locally.  Multiple devices per user are allowed,
but each fingerprint may only appear once per user.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.attendance import AttendanceRecord


class DevicePlatform(str, enum.Enum):
    """Client platform the device runs on."""

    ios = "ios"
    android = "android"
    web = "web"


class Device(Base):
    """
    A trusted (or untrusted) client device linked to a User.

    The ``device_fingerprint`` is a stable identifier generated on-device
    (e.g. a hash of hardware identifiers on mobile, or a persistent
    localStorage UUID on web).

    ``push_token`` stores the FCM / APNs token used to send push notifications.

    ``is_trusted`` starts as False and is set to True by an admin or after
    successful MFA confirmation.
    """

    __tablename__ = "devices"

    __table_args__ = (
        # Fingerprint must be unique per user (two users can own identical hardware)
        UniqueConstraint(
            "user_id",
            "device_fingerprint",
            name="uq_devices_user_fingerprint",
        ),
    )

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    # ------------------------------------------------------------------
    # Foreign key
    # ------------------------------------------------------------------
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ------------------------------------------------------------------
    # Device identity
    # ------------------------------------------------------------------
    device_fingerprint: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Stable device identifier generated by the client SDK.",
    )
    platform: Mapped[DevicePlatform] = mapped_column(
        Enum(DevicePlatform, name="device_platform", create_type=True),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Push notifications
    # ------------------------------------------------------------------
    push_token: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="FCM (Android/web) or APNs (iOS) push notification token.",
    )

    # ------------------------------------------------------------------
    # Trust state
    # ------------------------------------------------------------------
    is_trusted: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        comment="Set to true after admin approval or MFA confirmation.",
    )

    # ------------------------------------------------------------------
    # Activity tracking
    # ------------------------------------------------------------------
    last_seen_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp of the last API request from this device.",
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    user: Mapped["User"] = relationship(
        "User",
        back_populates="devices",
        lazy="selectin",
    )

    attendance_records: Mapped[List["AttendanceRecord"]] = relationship(
        "AttendanceRecord",
        back_populates="device",
        lazy="noload",
    )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def __repr__(self) -> str:
        return (
            f"<Device id={self.id} user_id={self.user_id} "
            f"platform={self.platform} trusted={self.is_trusted}>"
        )
